// Mock data — replaces DB entirely until the backend is wired up.
// Swap this file out for real Prisma calls when the database is ready.

export const MOCK_STUDENT = {
  id: 'mock-student-1',
  name: 'Thabo Nkosi',
  email: 'thabo@students.wits.ac.za',
  initials: 'TN',
  degree: 'BSc Computer Science',
  institution: 'University of the Witwatersrand',
  yearOfStudy: 3,
  graduationMonth: 'Nov',
  graduationYear: 2025,
  city: 'Johannesburg',
  province: 'Gauteng',
  salaryExpectation: 22000,
  availableFrom: 'Jan 2026',
  workTypePreferences: ['Full-time', 'Internship'],
  workLocationPrefs: ['Hybrid', 'Remote'],
  phone: '+27 82 345 6789',
  githubUrl: 'https://github.com/thabonkosi',
  linkedinUrl: 'https://linkedin.com/in/thabonkosi',
  slug: 'thabo-nkosi',
  passportCompletion: 83,
  bio: 'Final-year Computer Science student at Wits with a background in full-stack development. I build tools that solve real South African problems — my load shedding tracker has 1 200+ GitHub stars. Looking for a hybrid or remote role from January 2026.',
}

export const MOCK_SKILLS = [
  { id: '1', name: 'React', category: 'Frontend', level: 'VERIFIED' as const },
  { id: '2', name: 'Python', category: 'Languages', level: 'VERIFIED' as const },
  { id: '3', name: 'JavaScript', category: 'Languages', level: 'VERIFIED' as const },
  { id: '4', name: 'Node.js', category: 'Backend', level: 'VERIFIED' as const },
  { id: '5', name: 'TypeScript', category: 'Languages', level: 'CONFIDENT' as const },
  { id: '6', name: 'PostgreSQL', category: 'Database', level: 'CONFIDENT' as const },
  { id: '7', name: 'Docker', category: 'Infrastructure', level: 'LEARNING' as const },
  { id: '8', name: 'FastAPI', category: 'Backend', level: 'LEARNING' as const },
]

export const MOCK_PROJECTS = [
  {
    id: '1',
    title: 'SA Load Shedding Tracker',
    description: 'Real-time Eskom load shedding schedule tracker with push notifications and area-based search. 1 200+ GitHub stars. Used by students and residents across Gauteng.',
    githubUrl: 'https://github.com/thabonkosi/loadshedding',
    stars: '1 200+',
    type: 'Open source',
    skills: ['Python', 'FastAPI', 'React'],
  },
  {
    id: '2',
    title: 'StudySync',
    description: 'Real-time collaborative study platform. Students create shared study rooms, sync notes, and track progress together. Built for the SA student context where group study is common.',
    githubUrl: 'https://github.com/thabonkosi/studysync',
    stars: null,
    type: 'Personal project',
    skills: ['React', 'Node.js', 'PostgreSQL'],
  },
]

export const MOCK_ASSESSMENTS_COMPLETED = [
  {
    id: 'a1',
    title: 'Python & Data Structures',
    score: 91,
    completedAt: '3 days ago',
    questions: 20,
  },
]

export const MOCK_ASSESSMENTS_AVAILABLE = [
  { id: 'a2', title: 'React & Frontend Fundamentals', minutes: 18 },
  { id: 'a3', title: 'SQL & Database Design', minutes: 15 },
  { id: 'a4', title: 'JavaScript Fundamentals', minutes: 15 },
  { id: 'a5', title: 'Docker & Containers', minutes: 20, locked: true },
]

export const MOCK_MATCHES = [
  {
    id: 'm1',
    score: 94,
    role: 'Junior Software Engineer',
    company: 'Peach Payments',
    city: 'Cape Town',
    workType: 'Hybrid',
    salaryMin: 22000,
    salaryMax: 26000,
    startDate: 'Jan 2026',
    skills: ['React', 'Python', 'Node.js', 'PostgreSQL'],
    isNew: true,
  },
  {
    id: 'm2',
    score: 88,
    role: 'Graduate Developer',
    company: 'Takealot',
    city: 'Johannesburg',
    workType: 'Hybrid',
    salaryMin: 20000,
    salaryMax: 24000,
    startDate: 'Jan 2026',
    skills: ['Python', 'Node.js', 'Docker'],
    isNew: true,
  },
  {
    id: 'm3',
    score: 82,
    role: 'Software Engineer Intern',
    company: 'FNB Tech',
    city: 'Johannesburg',
    workType: 'In-office',
    salaryMin: 16000,
    salaryMax: 18000,
    startDate: 'Jan 2026',
    skills: ['Python', 'Spring Boot'],
    isNew: false,
  },
  {
    id: 'm4',
    score: 79,
    role: 'Junior Backend Developer',
    company: 'Shoprite Tech',
    city: 'Cape Town',
    workType: 'Remote',
    salaryMin: 20000,
    salaryMax: 25000,
    startDate: 'Mar 2026',
    skills: ['Python', 'FastAPI', 'PostgreSQL'],
    isNew: false,
  },
  {
    id: 'm5',
    score: 76,
    role: 'Frontend Developer (Graduate)',
    company: 'Woolworths Financial Services',
    city: 'Cape Town',
    workType: 'Hybrid',
    salaryMin: 19000,
    salaryMax: 23000,
    startDate: 'Feb 2026',
    skills: ['React', 'JavaScript', 'TypeScript'],
    isNew: false,
  },
  {
    id: 'm6',
    score: 72,
    role: 'Software Developer Trainee',
    company: 'Nedbank Digital',
    city: 'Johannesburg',
    workType: 'Hybrid',
    salaryMin: 17000,
    salaryMax: 21000,
    startDate: 'Jan 2026',
    skills: ['Python', 'SQL', 'Azure'],
    isNew: false,
  },
]

export const MOCK_PROFILE_VIEWS = 7

export const MOCK_ACTIVITY = [
  { color: 'bg-green-500', text: 'Peach Payments viewed your profile', time: '2 hours ago' },
  { color: 'bg-blue', text: 'New match: Shoprite Tech · Junior Backend Developer', time: 'Yesterday' },
  { color: 'bg-yellow', text: 'Python assessment completed — 91/100 ✓', time: '3 days ago' },
  { color: 'bg-gray-300', text: 'Profile created and passport started', time: '5 days ago' },
]

// Employer browse — mock candidates
export const MOCK_CANDIDATES = [
  {
    id: 'c1',
    name: 'Thabo Nkosi',
    initials: 'TN',
    avatarColor: 'bg-blue',
    degree: 'BSc Computer Science',
    institution: 'Wits',
    city: 'Jhb',
    province: 'Gauteng',
    salary: 22000,
    gradDate: 'Nov 2025',
    topSkill: 'React',
    topSkillSub: 'Python+',
    available: 'Jan 2026',
    workType: 'Hybrid',
    verified: true,
    isNew: true,
    slug: 'thabo-nkosi',
    skills: [{ name: 'React', verified: true }, { name: 'Python', verified: true }, { name: 'Node.js', verified: false }],
  },
  {
    id: 'c2',
    name: 'Kefilwe Molefe',
    initials: 'KM',
    avatarColor: 'bg-green-600',
    degree: 'BSc Information Technology',
    institution: 'UP',
    city: 'Pta',
    province: 'Gauteng',
    salary: 20000,
    gradDate: 'Nov 2025',
    topSkill: 'Python',
    topSkillSub: 'Django+',
    available: 'Jan 2026',
    workType: 'Remote',
    verified: true,
    isNew: false,
    slug: 'kefilwe-molefe',
    skills: [{ name: 'Python', verified: true }, { name: 'Django', verified: true }, { name: 'PostgreSQL', verified: false }],
  },
  {
    id: 'c3',
    name: 'Amara Petersen',
    initials: 'AP',
    avatarColor: 'bg-purple-600',
    degree: 'BSc Computer Science',
    institution: 'UCT',
    city: 'CPT',
    province: 'W. Cape',
    salary: 24000,
    gradDate: 'Jun 2025',
    topSkill: 'React',
    topSkillSub: 'TS+',
    available: 'Now',
    workType: 'Hybrid',
    verified: true,
    isNew: false,
    slug: 'amara-petersen',
    skills: [{ name: 'React', verified: true }, { name: 'JavaScript', verified: true }, { name: 'TypeScript', verified: false }],
  },
  {
    id: 'c4',
    name: 'Luyanda Booi',
    initials: 'LB',
    avatarColor: 'bg-teal-600',
    degree: 'Diploma Software Development',
    institution: 'CPUT',
    city: 'CPT',
    province: 'W. Cape',
    salary: 16000,
    gradDate: 'Nov 2025',
    topSkill: 'Java',
    topSkillSub: 'Spring+',
    available: 'Jan 2026',
    workType: 'In-office',
    verified: false,
    isNew: true,
    slug: 'luyanda-booi',
    skills: [{ name: 'Java', verified: false }, { name: 'Spring Boot', verified: false }, { name: 'MySQL', verified: false }],
  },
  {
    id: 'c5',
    name: 'Sipho Ntuli',
    initials: 'SN',
    avatarColor: 'bg-orange-500',
    degree: 'BSc Computer Engineering',
    institution: 'Wits',
    city: 'Jhb',
    province: 'Gauteng',
    salary: 25000,
    gradDate: 'Nov 2025',
    topSkill: 'C++',
    topSkillSub: 'Python+',
    available: 'Feb 2026',
    workType: 'Hybrid',
    verified: true,
    isNew: false,
    slug: 'sipho-ntuli',
    skills: [{ name: 'Python', verified: true }, { name: 'C++', verified: false }, { name: 'Linux', verified: false }],
  },
  {
    id: 'c6',
    name: 'Thandeka Mkhize',
    initials: 'TM',
    avatarColor: 'bg-sky-500',
    degree: 'BSc Computer Science',
    institution: 'UKZN',
    city: 'DBN',
    province: 'KZN',
    salary: 18000,
    gradDate: 'Jun 2025',
    topSkill: 'React',
    topSkillSub: 'Node.js+',
    available: 'Now',
    workType: 'Remote',
    verified: true,
    isNew: true,
    slug: 'thandeka-mkhize',
    skills: [{ name: 'React', verified: true }, { name: 'Node.js', verified: true }, { name: 'MongoDB', verified: false }],
  },
  {
    id: 'c7',
    name: 'Ruan van der Berg',
    initials: 'RV',
    avatarColor: 'bg-indigo-600',
    degree: 'BSc Computer Science',
    institution: 'Stellenbosch',
    city: 'CPT',
    province: 'W. Cape',
    salary: 26000,
    gradDate: 'Jun 2025',
    topSkill: 'TypeScript',
    topSkillSub: 'React+',
    available: 'Now',
    workType: 'Hybrid',
    verified: true,
    isNew: true,
    slug: 'ruan-van-der-berg',
    skills: [{ name: 'TypeScript', verified: true }, { name: 'React', verified: true }, { name: 'GraphQL', verified: false }],
  },
  {
    id: 'c8',
    name: 'Naledi Dlamini',
    initials: 'ND',
    avatarColor: 'bg-rose-500',
    degree: 'BSc Information Systems',
    institution: 'UP',
    city: 'Pta',
    province: 'Gauteng',
    salary: 19000,
    gradDate: 'Nov 2025',
    topSkill: 'SQL',
    topSkillSub: 'Python+',
    available: 'Jan 2026',
    workType: 'Hybrid',
    verified: true,
    isNew: false,
    slug: 'naledi-dlamini',
    skills: [{ name: 'SQL', verified: true }, { name: 'Python', verified: true }, { name: 'Tableau', verified: false }],
  },
  {
    id: 'c9',
    name: 'Jordan Fortuin',
    initials: 'JF',
    avatarColor: 'bg-amber-500',
    degree: 'BSc Computer Science',
    institution: 'UCT',
    city: 'CPT',
    province: 'W. Cape',
    salary: 23000,
    gradDate: 'Nov 2025',
    topSkill: 'Python',
    topSkillSub: 'ML+',
    available: 'Jan 2026',
    workType: 'Remote',
    verified: true,
    isNew: true,
    slug: 'jordan-fortuin',
    skills: [{ name: 'Python', verified: true }, { name: 'TensorFlow', verified: false }, { name: 'Pandas', verified: false }],
  },
  {
    id: 'c10',
    name: 'Mpho Sithole',
    initials: 'MS',
    avatarColor: 'bg-emerald-600',
    degree: 'BSc Software Engineering',
    institution: 'Wits',
    city: 'Jhb',
    province: 'Gauteng',
    salary: 21000,
    gradDate: 'Nov 2025',
    topSkill: 'Node.js',
    topSkillSub: 'React+',
    available: 'Jan 2026',
    workType: 'Hybrid',
    verified: true,
    isNew: false,
    slug: 'mpho-sithole',
    skills: [{ name: 'Node.js', verified: true }, { name: 'React', verified: false }, { name: 'PostgreSQL', verified: false }],
  },
  {
    id: 'c11',
    name: 'Chloé Rousseau',
    initials: 'CR',
    avatarColor: 'bg-pink-500',
    degree: 'BCom Information Systems',
    institution: 'Stellenbosch',
    city: 'CPT',
    province: 'W. Cape',
    salary: 17000,
    gradDate: 'Jun 2026',
    topSkill: 'JavaScript',
    topSkillSub: 'Vue+',
    available: 'Jun 2026',
    workType: 'Hybrid',
    verified: false,
    isNew: true,
    slug: 'chloe-rousseau',
    skills: [{ name: 'JavaScript', verified: false }, { name: 'Vue.js', verified: false }, { name: 'CSS', verified: false }],
  },
  {
    id: 'c12',
    name: 'Sibusiso Zulu',
    initials: 'SZ',
    avatarColor: 'bg-cyan-600',
    degree: 'Diploma IT',
    institution: 'DUT',
    city: 'DBN',
    province: 'KZN',
    salary: 15000,
    gradDate: 'Nov 2025',
    topSkill: 'Java',
    topSkillSub: 'Android+',
    available: 'Jan 2026',
    workType: 'In-office',
    verified: false,
    isNew: false,
    slug: 'sibusiso-zulu',
    skills: [{ name: 'Java', verified: false }, { name: 'Android', verified: false }, { name: 'MySQL', verified: false }],
  },
  {
    id: 'c13',
    name: 'Priya Naidoo',
    initials: 'PN',
    avatarColor: 'bg-violet-600',
    degree: 'BSc Computer Science',
    institution: 'UKZN',
    city: 'DBN',
    province: 'KZN',
    salary: 20000,
    gradDate: 'Nov 2025',
    topSkill: 'Python',
    topSkillSub: 'FastAPI+',
    available: 'Jan 2026',
    workType: 'Remote',
    verified: true,
    isNew: true,
    slug: 'priya-naidoo',
    skills: [{ name: 'Python', verified: true }, { name: 'FastAPI', verified: true }, { name: 'Docker', verified: false }],
  },
  {
    id: 'c14',
    name: 'Ethan Grobler',
    initials: 'EG',
    avatarColor: 'bg-lime-600',
    degree: 'BSc Computer Science',
    institution: 'UP',
    city: 'Pta',
    province: 'Gauteng',
    salary: 22000,
    gradDate: 'Nov 2025',
    topSkill: 'React',
    topSkillSub: 'Node.js+',
    available: 'Jan 2026',
    workType: 'Hybrid',
    verified: true,
    isNew: false,
    slug: 'ethan-grobler',
    skills: [{ name: 'React', verified: true }, { name: 'Node.js', verified: true }, { name: 'AWS', verified: false }],
  },
  {
    id: 'c15',
    name: 'Nomvula Khumalo',
    initials: 'NK',
    avatarColor: 'bg-fuchsia-600',
    degree: 'BSc Information Technology',
    institution: 'UJ',
    city: 'Jhb',
    province: 'Gauteng',
    salary: 18000,
    gradDate: 'Jun 2026',
    topSkill: 'Python',
    topSkillSub: 'Django+',
    available: 'Jun 2026',
    workType: 'Hybrid',
    verified: false,
    isNew: true,
    slug: 'nomvula-khumalo',
    skills: [{ name: 'Python', verified: false }, { name: 'Django', verified: false }, { name: 'HTML/CSS', verified: false }],
  },
  {
    id: 'c16',
    name: 'Aiden Jacobs',
    initials: 'AJ',
    avatarColor: 'bg-red-500',
    degree: 'BSc Electrical & Computer Engineering',
    institution: 'UCT',
    city: 'CPT',
    province: 'W. Cape',
    salary: 28000,
    gradDate: 'Jun 2025',
    topSkill: 'C++',
    topSkillSub: 'Linux+',
    available: 'Now',
    workType: 'In-office',
    verified: true,
    isNew: false,
    slug: 'aiden-jacobs',
    skills: [{ name: 'C++', verified: true }, { name: 'Linux', verified: true }, { name: 'Python', verified: false }],
  },
  {
    id: 'c17',
    name: 'Zanele Mokoena',
    initials: 'ZM',
    avatarColor: 'bg-teal-500',
    degree: 'BSc Computer Science',
    institution: 'Wits',
    city: 'Jhb',
    province: 'Gauteng',
    salary: 21000,
    gradDate: 'Nov 2025',
    topSkill: 'JavaScript',
    topSkillSub: 'React+',
    available: 'Jan 2026',
    workType: 'Remote',
    verified: true,
    isNew: false,
    slug: 'zanele-mokoena',
    skills: [{ name: 'JavaScript', verified: true }, { name: 'React', verified: false }, { name: 'TypeScript', verified: false }],
  },
  {
    id: 'c18',
    name: 'Marco da Silva',
    initials: 'MD',
    avatarColor: 'bg-orange-600',
    degree: 'Diploma Software Development',
    institution: 'CPUT',
    city: 'CPT',
    province: 'W. Cape',
    salary: 15000,
    gradDate: 'Nov 2025',
    topSkill: 'PHP',
    topSkillSub: 'Laravel+',
    available: 'Jan 2026',
    workType: 'In-office',
    verified: false,
    isNew: false,
    slug: 'marco-da-silva',
    skills: [{ name: 'PHP', verified: false }, { name: 'Laravel', verified: false }, { name: 'MySQL', verified: false }],
  },
  {
    id: 'c19',
    name: 'Lungelo Hadebe',
    initials: 'LH',
    avatarColor: 'bg-sky-600',
    degree: 'BSc Computer Science',
    institution: 'UKZN',
    city: 'DBN',
    province: 'KZN',
    salary: 19000,
    gradDate: 'Nov 2025',
    topSkill: 'React',
    topSkillSub: 'TypeScript+',
    available: 'Jan 2026',
    workType: 'Hybrid',
    verified: true,
    isNew: true,
    slug: 'lungelo-hadebe',
    skills: [{ name: 'React', verified: true }, { name: 'TypeScript', verified: false }, { name: 'Node.js', verified: false }],
  },
  {
    id: 'c20',
    name: 'Siyabonga Cele',
    initials: 'SC',
    avatarColor: 'bg-green-700',
    degree: 'BSc Software Engineering',
    institution: 'TUT',
    city: 'Pta',
    province: 'Gauteng',
    salary: 16500,
    gradDate: 'Nov 2025',
    topSkill: 'Java',
    topSkillSub: 'Spring+',
    available: 'Jan 2026',
    workType: 'Hybrid',
    verified: false,
    isNew: false,
    slug: 'siyabonga-cele',
    skills: [{ name: 'Java', verified: false }, { name: 'Spring Boot', verified: false }, { name: 'SQL', verified: false }],
  },
  {
    id: 'c21',
    name: 'Aisha Abrahams',
    initials: 'AA',
    avatarColor: 'bg-purple-500',
    degree: 'BSc Computer Science',
    institution: 'UCT',
    city: 'CPT',
    province: 'W. Cape',
    salary: 24000,
    gradDate: 'Jun 2025',
    topSkill: 'Python',
    topSkillSub: 'SQL+',
    available: 'Now',
    workType: 'Remote',
    verified: true,
    isNew: false,
    slug: 'aisha-abrahams',
    skills: [{ name: 'Python', verified: true }, { name: 'SQL', verified: true }, { name: 'Pandas', verified: false }],
  },
  {
    id: 'c22',
    name: 'Brendan October',
    initials: 'BO',
    avatarColor: 'bg-blue-700',
    degree: 'BCom Computer Science',
    institution: 'Stellenbosch',
    city: 'CPT',
    province: 'W. Cape',
    salary: 20000,
    gradDate: 'Nov 2025',
    topSkill: 'React',
    topSkillSub: 'TS+',
    available: 'Jan 2026',
    workType: 'Hybrid',
    verified: true,
    isNew: true,
    slug: 'brendan-october',
    skills: [{ name: 'React', verified: true }, { name: 'TypeScript', verified: false }, { name: 'Tailwind CSS', verified: false }],
  },
  {
    id: 'c23',
    name: 'Precious Mahlangu',
    initials: 'PM',
    avatarColor: 'bg-rose-600',
    degree: 'BSc Information Systems',
    institution: 'UJ',
    city: 'Jhb',
    province: 'Gauteng',
    salary: 17500,
    gradDate: 'Nov 2025',
    topSkill: 'SQL',
    topSkillSub: 'Excel+',
    available: 'Jan 2026',
    workType: 'In-office',
    verified: false,
    isNew: false,
    slug: 'precious-mahlangu',
    skills: [{ name: 'SQL', verified: false }, { name: 'Python', verified: false }, { name: 'Excel', verified: false }],
  },
  {
    id: 'c24',
    name: 'Dylan Swart',
    initials: 'DS',
    avatarColor: 'bg-indigo-500',
    degree: 'BSc Computer Science',
    institution: 'Stellenbosch',
    city: 'CPT',
    province: 'W. Cape',
    salary: 27000,
    gradDate: 'Jun 2025',
    topSkill: 'Go',
    topSkillSub: 'Docker+',
    available: 'Now',
    workType: 'Remote',
    verified: true,
    isNew: false,
    slug: 'dylan-swart',
    skills: [{ name: 'Go', verified: true }, { name: 'Docker', verified: true }, { name: 'Linux', verified: false }],
  },
  {
    id: 'c25',
    name: 'Ntombi Shabalala',
    initials: 'NS',
    avatarColor: 'bg-amber-600',
    degree: 'BSc Computer Science',
    institution: 'Wits',
    city: 'Jhb',
    province: 'Gauteng',
    salary: 20000,
    gradDate: 'Nov 2025',
    topSkill: 'Python',
    topSkillSub: 'Node.js+',
    available: 'Jan 2026',
    workType: 'Hybrid',
    verified: true,
    isNew: true,
    slug: 'ntombi-shabalala',
    skills: [{ name: 'Python', verified: true }, { name: 'Node.js', verified: false }, { name: 'MongoDB', verified: false }],
  },
  {
    id: 'c26',
    name: 'Imaan Hendricks',
    initials: 'IH',
    avatarColor: 'bg-teal-700',
    degree: 'BSc Information Technology',
    institution: 'CPUT',
    city: 'CPT',
    province: 'W. Cape',
    salary: 16000,
    gradDate: 'Jun 2026',
    topSkill: 'JavaScript',
    topSkillSub: 'HTML/CSS+',
    available: 'Jun 2026',
    workType: 'Hybrid',
    verified: false,
    isNew: false,
    slug: 'imaan-hendricks',
    skills: [{ name: 'JavaScript', verified: false }, { name: 'HTML/CSS', verified: false }, { name: 'React', verified: false }],
  },
  {
    id: 'c27',
    name: 'Karabo Modise',
    initials: 'KM2',
    avatarColor: 'bg-emerald-500',
    degree: 'BSc Computer Engineering',
    institution: 'UP',
    city: 'Pta',
    province: 'Gauteng',
    salary: 23000,
    gradDate: 'Nov 2025',
    topSkill: 'C++',
    topSkillSub: 'Python+',
    available: 'Jan 2026',
    workType: 'Hybrid',
    verified: true,
    isNew: false,
    slug: 'karabo-modise',
    skills: [{ name: 'C++', verified: true }, { name: 'Python', verified: false }, { name: 'Git', verified: false }],
  },
  {
    id: 'c28',
    name: 'Simone van Wyk',
    initials: 'SW',
    avatarColor: 'bg-pink-600',
    degree: 'BSc Computer Science',
    institution: 'UCT',
    city: 'CPT',
    province: 'W. Cape',
    salary: 25000,
    gradDate: 'Jun 2025',
    topSkill: 'React',
    topSkillSub: 'GraphQL+',
    available: 'Now',
    workType: 'Remote',
    verified: true,
    isNew: true,
    slug: 'simone-van-wyk',
    skills: [{ name: 'React', verified: true }, { name: 'GraphQL', verified: true }, { name: 'TypeScript', verified: false }],
  },
  {
    id: 'c29',
    name: 'Oratile Moagi',
    initials: 'OM',
    avatarColor: 'bg-violet-500',
    degree: 'Diploma Web Development',
    institution: 'WeThinkCode_',
    city: 'Jhb',
    province: 'Gauteng',
    salary: 18000,
    gradDate: 'Nov 2025',
    topSkill: 'Python',
    topSkillSub: 'JavaScript+',
    available: 'Jan 2026',
    workType: 'Hybrid',
    verified: true,
    isNew: true,
    slug: 'oratile-moagi',
    skills: [{ name: 'Python', verified: true }, { name: 'JavaScript', verified: false }, { name: 'Git', verified: false }],
  },
  {
    id: 'c30',
    name: 'Heinrich Müller',
    initials: 'HM',
    avatarColor: 'bg-slate-600',
    degree: 'BSc Electronic Engineering',
    institution: 'Stellenbosch',
    city: 'CPT',
    province: 'W. Cape',
    salary: 28000,
    gradDate: 'Jun 2025',
    topSkill: 'C++',
    topSkillSub: 'Python+',
    available: 'Now',
    workType: 'Hybrid',
    verified: true,
    isNew: false,
    slug: 'heinrich-muller',
    skills: [{ name: 'C++', verified: true }, { name: 'Python', verified: true }, { name: 'MATLAB', verified: false }],
  },
]

// ── Employer: roles & pipeline ─────────────────────────────────────────────

export const MOCK_ROLE = {
  companySlug: 'peach-payments',
  roleSlug: 'junior-software-engineer',
  companyName: 'Peach Payments',
  companyInitials: 'PP',
  companyColor: 'bg-navy',
  industry: 'Fintech',
  title: 'Junior Software Engineer',
  location: 'Cape Town',
  workType: 'Hybrid' as const,
  roleType: 'Full-time' as const,
  salaryMin: 22000,
  salaryMax: 26000,
  stack: ['React', 'Node.js', 'TypeScript'],
  description: "We're building the payments infrastructure South Africa runs on. As a junior software engineer on the integrations team, you'll work on the APIs and dashboards that help thousands of merchants accept payments online. You'll be mentored by senior engineers, ship real code in your first week, and work on problems that actually matter.\n\nWe care about learning speed, not just what's on your CV. If you're curious, build things in your spare time, and want to work somewhere that takes engineering seriously — apply.",
  gradYears: ['2025', '2026'],
  screeningQuestions: [
    { id: 'sq1', question: 'Have you worked with any payment APIs or financial systems before?', type: 'yesno' as const },
    { id: 'sq2', question: 'Are you able to work from our Cape Town office at least 3 days per week?', type: 'yesno' as const },
    { id: 'sq3', question: 'In one sentence, what side project or university project are you most proud of?', type: 'short' as const },
  ],
  postedAt: '2026-06-01',
  expiresAt: '2026-07-31',
  applicationCount: 12,
  contactName: 'Naledi Dlamini',
  contactTitle: 'Head of Talent',
}

export type PipelineStage = 'new' | 'screening' | 'shortlisted' | 'interview' | 'offer' | 'hired' | 'declined'

export interface PipelineApplication {
  id: string
  candidateSlug: string
  candidateName: string
  initials: string
  avatarColor: string
  city: string
  salary: number
  gradDate: string
  institution: string
  stack: string[]
  verifiedSkills?: string[]
  passportCompletion: number
  stage: PipelineStage
  appliedAt: string
  isNew: boolean
  verified: boolean
  bio?: string
  projects?: { title: string; description: string; githubUrl?: string; skills: string[] }[]
  assessments?: { title: string; score: number }[]
  githubUrl?: string
  linkedinUrl?: string
  screeningAnswers: { question: string; answer: string }[]
  notes?: string
}

export const MOCK_APPLICATIONS: PipelineApplication[] = [
  { id: 'app1', candidateSlug: 'thabo-nkosi', candidateName: 'Thabo Nkosi', initials: 'TN', avatarColor: 'bg-blue', city: 'Jhb', salary: 22000, gradDate: 'Nov 2025', institution: 'Wits', stack: ['React', 'Python', 'Node.js', 'TypeScript', 'PostgreSQL'], verifiedSkills: ['React', 'Python', 'Node.js'], passportCompletion: 83, stage: 'new', appliedAt: '2 hours ago', isNew: true, verified: true, bio: 'Final-year Computer Science student at Wits with a focus on full-stack development. I build tools that solve real South African problems — my load shedding tracker has 1 200+ GitHub stars. Looking for a hybrid or remote role from January 2026.', projects: [{ title: 'SA Load Shedding Tracker', description: 'Real-time Eskom schedule tracker with push notifications and area-based search. 1 200+ GitHub stars, used by residents across Gauteng.', githubUrl: 'https://github.com/thabonkosi/loadshedding', skills: ['Python', 'FastAPI', 'React'] }, { title: 'StudySync', description: 'Real-time collaborative study platform for SA students. Shared rooms, synced notes, and progress tracking.', githubUrl: 'https://github.com/thabonkosi/studysync', skills: ['React', 'Node.js', 'PostgreSQL'] }], assessments: [{ title: 'Python & Data Structures', score: 91 }], githubUrl: 'https://github.com/thabonkosi', linkedinUrl: 'https://linkedin.com/in/thabonkosi', screeningAnswers: [{ question: 'Have you worked with any payment APIs?', answer: 'No' }, { question: 'Can you work from Cape Town office?', answer: 'Yes' }, { question: 'Most proud project?', answer: 'SA Load Shedding Tracker — 1 200+ GitHub stars, used by thousands of residents.' }] },
  { id: 'app2', candidateSlug: 'amara-petersen', candidateName: 'Amara Petersen', initials: 'AP', avatarColor: 'bg-purple-600', city: 'CPT', salary: 24000, gradDate: 'Jun 2025', institution: 'UCT', stack: ['React', 'TypeScript', 'JavaScript', 'GraphQL'], verifiedSkills: ['React', 'JavaScript', 'TypeScript'], passportCompletion: 91, stage: 'new', appliedAt: '5 hours ago', isNew: true, verified: true, bio: 'UCT Computer Science graduate with strong frontend skills and payment API experience. Built production React apps for two Cape Town companies. Available immediately.', projects: [{ title: 'Bursary Tracker Dashboard', description: 'React + TypeScript dashboard for a non-profit managing 400+ bursary applications across 12 SA universities.', skills: ['React', 'TypeScript', 'Supabase'] }, { title: 'Yoco Checkout Integration', description: 'Full e-commerce checkout flow with Yoco payments for a Cape Town retailer, currently processing live transactions.', skills: ['React', 'Node.js', 'Yoco API'] }], assessments: [{ title: 'React & Frontend Fundamentals', score: 88 }, { title: 'JavaScript Fundamentals', score: 94 }], githubUrl: 'https://github.com/amarapetersen', linkedinUrl: 'https://linkedin.com/in/amarapetersen', screeningAnswers: [{ question: 'Have you worked with any payment APIs?', answer: 'Yes' }, { question: 'Can you work from Cape Town office?', answer: 'Yes' }, { question: 'Most proud project?', answer: 'Built a React dashboard for a non-profit that tracks bursary applications.' }] },
  { id: 'app3', candidateSlug: 'ruan-van-der-berg', candidateName: 'Ruan van der Berg', initials: 'RV', avatarColor: 'bg-indigo-600', city: 'CPT', salary: 26000, gradDate: 'Jun 2025', institution: 'Stellenbosch', stack: ['TypeScript', 'React', 'GraphQL', 'Node.js'], verifiedSkills: ['TypeScript', 'React'], passportCompletion: 88, stage: 'new', appliedAt: '1 day ago', isNew: true, verified: true, bio: 'Stellenbosch CS graduate passionate about typed systems and developer tooling. My open-source TypeScript library has 300+ weekly npm downloads. Strong GraphQL experience from internship at a CPT startup.', projects: [{ title: 'ts-sa-id', description: 'Open-source TypeScript library for validating and parsing South African ID numbers. 300+ weekly npm downloads.', githubUrl: 'https://github.com/ruanvdberg/ts-sa-id', skills: ['TypeScript', 'Node.js'] }], assessments: [{ title: 'React & Frontend Fundamentals', score: 82 }], githubUrl: 'https://github.com/ruanvdberg', linkedinUrl: 'https://linkedin.com/in/ruanvdberg', screeningAnswers: [{ question: 'Have you worked with any payment APIs?', answer: 'No' }, { question: 'Can you work from Cape Town office?', answer: 'Yes' }, { question: 'Most proud project?', answer: 'Open-source TypeScript utility library with 300+ npm downloads per week.' }] },
  { id: 'app4', candidateSlug: 'brendan-october', candidateName: 'Brendan October', initials: 'BO', avatarColor: 'bg-blue-700', city: 'CPT', salary: 20000, gradDate: 'Nov 2025', institution: 'Stellenbosch', stack: ['React', 'TypeScript', 'Tailwind CSS'], passportCompletion: 74, stage: 'new', appliedAt: '1 day ago', isNew: true, verified: true, screeningAnswers: [{ question: 'Have you worked with any payment APIs?', answer: 'No' }, { question: 'Can you work from Cape Town office?', answer: 'Yes' }, { question: 'Most proud project?', answer: 'Final year project: a real-time taxi tracker for Stellenbosch using React + WebSockets.' }] },
  { id: 'app5', candidateSlug: 'thandeka-mkhize', candidateName: 'Thandeka Mkhize', initials: 'TM', avatarColor: 'bg-sky-500', city: 'DBN', salary: 18000, gradDate: 'Jun 2025', institution: 'UKZN', stack: ['React', 'Node.js', 'MongoDB'], passportCompletion: 79, stage: 'screening', appliedAt: '2 days ago', isNew: false, verified: true, screeningAnswers: [{ question: 'Have you worked with any payment APIs?', answer: 'No' }, { question: 'Can you work from Cape Town office?', answer: 'Yes — willing to relocate' }, { question: 'Most proud project?', answer: 'Full-stack job board for local businesses in KZN, currently live.' }] },
  { id: 'app6', candidateSlug: 'aisha-abrahams', candidateName: 'Aisha Abrahams', initials: 'AA', avatarColor: 'bg-purple-500', city: 'CPT', salary: 24000, gradDate: 'Jun 2025', institution: 'UCT', stack: ['Python', 'SQL', 'Pandas'], passportCompletion: 95, stage: 'screening', appliedAt: '3 days ago', isNew: false, verified: true, screeningAnswers: [{ question: 'Have you worked with any payment APIs?', answer: 'Yes — Stripe sandbox in a personal project' }, { question: 'Can you work from Cape Town office?', answer: 'Yes' }, { question: 'Most proud project?', answer: 'Python data pipeline for analysing student loan repayment patterns (Honours thesis).' }] },
  { id: 'app7', candidateSlug: 'dylan-swart', candidateName: 'Dylan Swart', initials: 'DS', avatarColor: 'bg-indigo-500', city: 'CPT', salary: 27000, gradDate: 'Jun 2025', institution: 'Stellenbosch', stack: ['Go', 'Docker', 'Linux'], passportCompletion: 87, stage: 'screening', appliedAt: '3 days ago', isNew: false, verified: true, screeningAnswers: [{ question: 'Have you worked with any payment APIs?', answer: 'No' }, { question: 'Can you work from Cape Town office?', answer: 'Yes' }, { question: 'Most proud project?', answer: 'Go microservice that processes 10k+ events per second, deployed on Kubernetes.' }] },
  { id: 'app8', candidateSlug: 'jordan-fortuin', candidateName: 'Jordan Fortuin', initials: 'JF', avatarColor: 'bg-amber-500', city: 'CPT', salary: 23000, gradDate: 'Nov 2025', institution: 'UCT', stack: ['Python', 'TensorFlow', 'Pandas'], passportCompletion: 68, stage: 'shortlisted', appliedAt: '4 days ago', isNew: false, verified: true, screeningAnswers: [{ question: 'Have you worked with any payment APIs?', answer: 'No' }, { question: 'Can you work from Cape Town office?', answer: 'Yes' }, { question: 'Most proud project?', answer: 'ML model predicting load shedding impact on small businesses (72% accuracy).' }] },
  { id: 'app9', candidateSlug: 'aiden-jacobs', candidateName: 'Aiden Jacobs', initials: 'AJ', avatarColor: 'bg-red-500', city: 'CPT', salary: 28000, gradDate: 'Jun 2025', institution: 'UCT', stack: ['C++', 'Linux', 'Python'], passportCompletion: 81, stage: 'shortlisted', appliedAt: '5 days ago', isNew: false, verified: true, screeningAnswers: [{ question: 'Have you worked with any payment APIs?', answer: 'No' }, { question: 'Can you work from Cape Town office?', answer: 'Yes' }, { question: 'Most proud project?', answer: 'Low-latency trading simulator built in C++ for my Computer Engineering capstone.' }] },
  { id: 'app10', candidateSlug: 'simone-van-wyk', candidateName: 'Simone van Wyk', initials: 'SV', avatarColor: 'bg-pink-500', city: 'CPT', salary: 23000, gradDate: 'Jun 2025', institution: 'UCT', stack: ['React', 'GraphQL', 'TypeScript'], passportCompletion: 92, stage: 'shortlisted', appliedAt: '5 days ago', isNew: false, verified: true, screeningAnswers: [{ question: 'Have you worked with any payment APIs?', answer: 'Yes — built a checkout flow with Yoco in a freelance project' }, { question: 'Can you work from Cape Town office?', answer: 'Yes' }, { question: 'Most proud project?', answer: 'Freelance e-commerce site with integrated Yoco payments, still running for a CPT bakery.' }] },
  { id: 'app11', candidateSlug: 'lungelo-hadebe', candidateName: 'Lungelo Hadebe', initials: 'LH', avatarColor: 'bg-sky-600', city: 'DBN', salary: 19000, gradDate: 'Nov 2025', institution: 'UKZN', stack: ['React', 'TypeScript', 'Node.js'], passportCompletion: 71, stage: 'interview', appliedAt: '1 week ago', isNew: false, verified: true, screeningAnswers: [{ question: 'Have you worked with any payment APIs?', answer: 'No' }, { question: 'Can you work from Cape Town office?', answer: 'Yes — plan to relocate in January' }, { question: 'Most proud project?', answer: 'Built a React + Node.js platform for a Durban school to manage homework submissions.' }] },
  { id: 'app12', candidateSlug: 'kefilwe-molefe', candidateName: 'Kefilwe Molefe', initials: 'KM', avatarColor: 'bg-green-600', city: 'Pta', salary: 20000, gradDate: 'Nov 2025', institution: 'UP', stack: ['Python', 'Django', 'PostgreSQL'], passportCompletion: 85, stage: 'interview', appliedAt: '1 week ago', isNew: false, verified: true, screeningAnswers: [{ question: 'Have you worked with any payment APIs?', answer: 'Yes — PayFast in a Django project' }, { question: 'Can you work from Cape Town office?', answer: 'Yes — willing to relocate' }, { question: 'Most proud project?', answer: 'Django REST API for a student marketplace app, used by 200+ UP students.' }] },
]

export const MOCK_EMPLOYER_ROLES = [
  {
    id: 'r1',
    companySlug: 'peach-payments',
    roleSlug: 'junior-software-engineer',
    title: 'Junior Software Engineer',
    location: 'Cape Town · Hybrid',
    roleType: 'Full-time',
    salaryMin: 22000,
    salaryMax: 26000,
    stack: ['React', 'Node.js', 'TypeScript'],
    applicationCount: 12,
    newCount: 4,
    status: 'active' as const,
    postedAt: 'Jun 1',
  },
]
