import { MOCK_STUDENT, MOCK_SKILLS, MOCK_PROJECTS, MOCK_ASSESSMENTS_COMPLETED } from '@/lib/mock-data'
import { notFound } from 'next/navigation'
import { formatRand } from '@/lib/utils'
import Link from 'next/link'
import PrintButton from './PrintButton'

export async function generateMetadata({ params }: { params: { slug: string } }) {
  if (params.slug !== MOCK_STUDENT.slug) return { title: 'Not found' }
  return { title: `${MOCK_STUDENT.name} — CV · askJeni` }
}

export default function CVPage({ params }: { params: { slug: string } }) {
  if (params.slug !== MOCK_STUDENT.slug) notFound()

  const verifiedSkills = MOCK_SKILLS.filter(s => s.level === 'VERIFIED')
  const confidentSkills = MOCK_SKILLS.filter(s => s.level === 'CONFIDENT')

  return (
    <>
      {/* Print button — hidden when printing */}
      <div className="no-print fixed top-0 left-0 right-0 bg-navy h-12 flex items-center justify-between px-8 z-50">
        <Link href={`/profile/${MOCK_STUDENT.slug}`} className="text-white/60 text-sm hover:text-white">← Back to profile</Link>
        <div className="flex items-center gap-3">
          <span className="text-white/40 text-xs">One-page CV · Generated by askJeni</span>
          <PrintButton />
        </div>
      </div>

      {/* CV SHEET — A4 proportions */}
      <div className="cv-page bg-white mx-auto" style={{ maxWidth: 794, minHeight: 1123, paddingTop: 56 }}>
        <div className="cv-inner" style={{ padding: '40px 48px 40px 48px' }}>

          {/* HEADER */}
          <div className="cv-header" style={{ borderBottom: '2.5px solid #0D1B2A', paddingBottom: 20, marginBottom: 20 }}>
            <div style={{ display: 'flex', gap: 20, alignItems: 'flex-start' }}>

              {/* Profile photo */}
              <div style={{
                width: 80, height: 80, borderRadius: 8, flexShrink: 0,
                background: '#2563EB', display: 'flex', alignItems: 'center',
                justifyContent: 'center', border: '2px solid #E5EAF0',
              }}>
                <span style={{ fontSize: 26, fontWeight: 800, color: '#fff', letterSpacing: '-1px' }}>
                  {MOCK_STUDENT.initials}
                </span>
              </div>

              {/* Name + degree */}
              <div style={{ flex: 1 }}>
                <h1 style={{ fontSize: 28, fontWeight: 800, color: '#0D1B2A', margin: 0, letterSpacing: '-0.5px' }}>
                  {MOCK_STUDENT.name}
                </h1>
                <p style={{ fontSize: 13, color: '#506070', margin: '4px 0 0', fontWeight: 500 }}>
                  {MOCK_STUDENT.degree} · {MOCK_STUDENT.institution}
                </p>
                <p style={{ fontSize: 12, color: '#8EA3BB', margin: '2px 0 0' }}>
                  Graduating {MOCK_STUDENT.graduationMonth} {MOCK_STUDENT.graduationYear} · {MOCK_STUDENT.city}, {MOCK_STUDENT.province}
                </p>
              </div>

              {/* Contact + verified badge */}
              <div style={{ textAlign: 'right', flexShrink: 0 }}>
                <div style={{
                  display: 'inline-flex', alignItems: 'center', gap: 6,
                  background: '#F0F9F4', border: '1px solid #BBF7D0',
                  borderRadius: 20, padding: '4px 12px', marginBottom: 8,
                }}>
                  <span style={{ fontSize: 11, fontWeight: 700, color: '#16A34A' }}>✓ askJeni Verified · {MOCK_STUDENT.passportCompletion}% passport</span>
                </div>
                <div style={{ fontSize: 11, color: '#8EA3BB', lineHeight: 1.8 }}>
                  <div>{MOCK_STUDENT.phone}</div>
                  <div>{MOCK_STUDENT.email}</div>
                  <div>
                    <a href={MOCK_STUDENT.githubUrl} style={{ color: '#2563EB' }}>github.com/thabonkosi</a>
                    {' · '}
                    <a href={MOCK_STUDENT.linkedinUrl} style={{ color: '#2563EB' }}>linkedin.com/in/thabonkosi</a>
                  </div>
                </div>
              </div>

            </div>
          </div>

          {/* SIGNAL ROW */}
          <div style={{
            display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)',
            gap: 0, marginBottom: 24,
            border: '1px solid #E5EAF0', borderRadius: 8, overflow: 'hidden',
          }}>
            {[
              { label: 'Available from', value: MOCK_STUDENT.availableFrom },
              { label: 'Salary expectation', value: `${formatRand(MOCK_STUDENT.salaryExpectation)} / month` },
              { label: 'Work preference', value: MOCK_STUDENT.workLocationPrefs.join(' · ') },
              { label: 'Work type', value: MOCK_STUDENT.workTypePreferences.join(' · ') },
            ].map((item, i, arr) => (
              <div key={item.label} style={{
                padding: '10px 14px',
                borderRight: i < arr.length - 1 ? '1px solid #E5EAF0' : 'none',
                background: '#FAFBFC',
              }}>
                <div style={{ fontSize: 9, fontWeight: 700, color: '#8EA3BB', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 3 }}>{item.label}</div>
                <div style={{ fontSize: 12, fontWeight: 600, color: '#0D1B2A' }}>{item.value}</div>
              </div>
            ))}
          </div>

          {/* TWO COLUMN LAYOUT */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 260px', gap: 28 }}>

            {/* LEFT COLUMN */}
            <div>

              {/* ABOUT */}
              <Section title="About">
                <p style={{ fontSize: 12, color: '#374151', lineHeight: 1.65, margin: 0 }}>{MOCK_STUDENT.bio}</p>
              </Section>

              {/* PROJECTS */}
              <Section title="Projects">
                {MOCK_PROJECTS.map(p => (
                  <div key={p.id} style={{ marginBottom: 14 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 3 }}>
                      <span style={{ fontSize: 13, fontWeight: 700, color: '#0D1B2A' }}>{p.title}</span>
                      <a href={p.githubUrl} style={{ fontSize: 10, color: '#2563EB' }}>↗ GitHub</a>
                    </div>
                    <p style={{ fontSize: 11.5, color: '#506070', lineHeight: 1.6, margin: '0 0 5px' }}>{p.description}</p>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                      {p.skills.map(s => (
                        <span key={s} style={{
                          fontSize: 10, fontWeight: 600, color: '#2563EB',
                          background: '#EFF6FF', borderRadius: 4, padding: '2px 7px',
                        }}>{s}</span>
                      ))}
                    </div>
                  </div>
                ))}
              </Section>

              {/* EDUCATION */}
              <Section title="Education">
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
                  <div>
                    <div style={{ fontSize: 13, fontWeight: 700, color: '#0D1B2A' }}>{MOCK_STUDENT.degree}</div>
                    <div style={{ fontSize: 12, color: '#506070', marginTop: 2 }}>{MOCK_STUDENT.institution}</div>
                  </div>
                  <div style={{ fontSize: 11, color: '#8EA3BB', textAlign: 'right' }}>
                    <div>Year {MOCK_STUDENT.yearOfStudy}</div>
                    <div>Graduating {MOCK_STUDENT.graduationMonth} {MOCK_STUDENT.graduationYear}</div>
                  </div>
                </div>
              </Section>

            </div>

            {/* RIGHT COLUMN */}
            <div>

              {/* VERIFIED SKILLS */}
              <Section title="Verified Skills">
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 5, marginBottom: verifiedSkills.length ? 10 : 0 }}>
                  {verifiedSkills.map(s => (
                    <span key={s.id} style={{
                      fontSize: 11, fontWeight: 600,
                      background: '#F0FDF4', color: '#16A34A',
                      border: '1px solid #BBF7D0',
                      borderRadius: 20, padding: '3px 10px',
                    }}>✓ {s.name}</span>
                  ))}
                </div>
                {confidentSkills.length > 0 && (
                  <>
                    <div style={{ fontSize: 9, fontWeight: 700, color: '#8EA3BB', textTransform: 'uppercase', letterSpacing: '0.06em', margin: '10px 0 6px' }}>Self-declared</div>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 5 }}>
                      {confidentSkills.map(s => (
                        <span key={s.id} style={{
                          fontSize: 11, fontWeight: 600,
                          background: '#FFFBEB', color: '#92400E',
                          border: '1px solid #FDE68A',
                          borderRadius: 20, padding: '3px 10px',
                        }}>{s.name}</span>
                      ))}
                    </div>
                  </>
                )}
              </Section>

              {/* ASSESSMENTS */}
              <Section title="Skill Assessments">
                {MOCK_ASSESSMENTS_COMPLETED.map(a => (
                  <div key={a.id} style={{ marginBottom: 10 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
                      <span style={{ fontSize: 11.5, fontWeight: 600, color: '#0D1B2A', flex: 1, paddingRight: 8 }}>{a.title}</span>
                      <span style={{ fontSize: 12, fontWeight: 800, color: '#16A34A' }}>{a.score}/100</span>
                    </div>
                    <div style={{ height: 4, background: '#E5E7EB', borderRadius: 4, overflow: 'hidden' }}>
                      <div style={{ height: '100%', width: `${a.score}%`, background: '#16A34A', borderRadius: 4 }} />
                    </div>
                    <div style={{ fontSize: 10, color: '#8EA3BB', marginTop: 3 }}>askJeni proctored · {a.questions} questions</div>
                  </div>
                ))}
              </Section>

              {/* LINKS */}
              <Section title="Links">
                <div style={{ fontSize: 11.5, lineHeight: 2 }}>
                  <div><a href={MOCK_STUDENT.githubUrl} style={{ color: '#2563EB' }}>↗ GitHub</a></div>
                  <div><a href={MOCK_STUDENT.linkedinUrl} style={{ color: '#2563EB' }}>↗ LinkedIn</a></div>
                </div>
              </Section>

            </div>
          </div>

          {/* FOOTER */}
          <div style={{
            marginTop: 32, paddingTop: 14, borderTop: '1px solid #E5EAF0',
            display: 'flex', justifyContent: 'space-between', alignItems: 'center',
          }}>
            <span style={{ fontSize: 10, color: '#8EA3BB' }}>Generated by askJeni · askjeni.co.za</span>
            <span style={{ fontSize: 10, color: '#8EA3BB' }}>Skills verified independently · {new Date().toLocaleDateString('en-ZA', { month: 'long', year: 'numeric' })}</span>
          </div>

        </div>
      </div>

      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { margin: 0; }
          .cv-page { max-width: 100% !important; box-shadow: none !important; }
          @page { margin: 0; size: A4; }
        }
        @media screen {
          body { background: #F7F9FC; }
          .cv-page { box-shadow: 0 4px 40px rgba(0,0,0,0.12); margin-top: 0; }
        }
      `}</style>
    </>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 20 }}>
      <div style={{
        fontSize: 9, fontWeight: 800, color: '#8EA3BB',
        textTransform: 'uppercase', letterSpacing: '0.08em',
        marginBottom: 8, paddingBottom: 5,
        borderBottom: '1px solid #E5EAF0',
      }}>
        {title}
      </div>
      {children}
    </div>
  )
}
